#!/usr/bin/env python3
"""Generate a full affiliate content set for one product via the 7-prompt chain.

Runs the affiliate-content-prompts.md chain (#2 review angles -> #3 blog outline
-> #4 video scripts -> #5 comparison -> #6 link hub -> #7 30-day calendar) against
a single product and writes a Markdown content set to marketing-campaigns/.

Usage:
    python generate_content_set.py --product "penkou Portable Neck Fan, Hands Free..."
    python generate_content_set.py --product "..." --asin B0XXXXXXXX --dry-run
    python generate_content_set.py --selftest

Env: ANTHROPIC_API_KEY (loaded from .env). Skipped when --dry-run is passed.
"""
from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

from dotenv import load_dotenv

load_dotenv(override=True)

HERE = Path(__file__).resolve().parent
OUT_DIR = HERE / "marketing-campaigns"
DEFAULT_TAG = "hotproduct033-20"
DEFAULT_MODEL = os.environ.get("CONTENT_SET_MODEL", "claude-sonnet-4-6")

SYSTEM = (
    "You are an Amazon affiliate content strategist for HotProducts. Voice: upbeat, "
    "funny, lightly viral, but always HONEST (name real drawbacks). Audience: everyday "
    "consumers. Every page needs an FTC affiliate disclosure and uses 'Check Price on "
    "Amazon' instead of stating a price. Output clean Markdown only."
)

CHAIN = """Generate a complete affiliate content set for this product:

PRODUCT: {product}
{asin_line}AFFILIATE TAG: {tag}

Produce these sections as Markdown, in order:

## #2 - 10 Review Angles
10 angles around real buyer questions, problems solved, comparisons, and who should
avoid it. Note which channel each fits (blog / video hook / comparison / Pinterest).

## #3 - SEO Blog Outline
Title "Best [product type] for [audience]", primary + secondary keywords, full H1/H2/H3
outline including comparison table, buyer guide, honest drawbacks, who-should-skip, FAQ
(snippet bait), and explicit affiliate-disclosure placement.

## #4 - 5 Short-Form Video Scripts
Each 20-35s: hook, problem, feature/demo, ONE honest drawback, CTA to the link hub.

## #5 - Comparison Copy
This product vs a cheaper/simpler alternative for a beginner buyer: pros, cons, best use
case, final recommendation, CTA.

## #6 - Link Hub (by buyer problem)
A hub organized by the buyer's PROBLEM (not product type), with disclosure pinned top and
links using tag={tag}.

## #7 - 30-Day Content Calendar
A 4-week table (Day | Video hook | Blog/Long-form | Pinterest pin title) mapped to the
funnel: Wk1 awareness, Wk2 problem-solution, Wk3 social proof, Wk4 conversion.
"""


def slug(name: str) -> str:
    """Filesystem-safe slug from a product name (first ~6 meaningful words)."""
    words = re.findall(r"[a-z0-9]+", name.lower())[:6]
    return "-".join(words) or "product"


def build_prompt(product: str, asin: str, tag: str) -> str:
    asin_line = f"ASIN: {asin}\n" if asin else ""
    return CHAIN.format(product=product, asin_line=asin_line, tag=tag)


def header(product: str, asin: str, tag: str) -> str:
    asin_part = f" - ASIN {asin}" if asin else ""
    return (
        f"# {product[:80]} - Full Content Set\n\n"
        f"Product: {product}{asin_part}\n"
        f"Tracking: `?tag={tag}` - FTC disclosure required on every page - "
        f"'Check Price on Amazon' (never show price)\n\n"
        f"Generated by generate_content_set.py (chain #2 -> #7). "
        f"See marketing-campaigns/affiliate-content-prompts.md.\n\n---\n\n"
    )


def generate(product: str, asin: str, tag: str, dry_run: bool, model: str) -> str:
    prompt = build_prompt(product, asin, tag)
    if dry_run:
        return (
            "_[DRY RUN] No API call. The chain prompt that would be sent:_\n\n"
            "```\n" + prompt + "\n```\n"
        )
    # Anthropic SDK is already a project dependency (see instagram/ad_creative_gen.py).
    from anthropic import Anthropic

    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        sys.exit("ERROR: ANTHROPIC_API_KEY not set (add to .env or use --dry-run)")
    resp = Anthropic(api_key=api_key).messages.create(
        model=model,
        max_tokens=8000,
        temperature=0.8,
        system=SYSTEM,
        messages=[{"role": "user", "content": prompt}],
    )
    return "".join(b.text for b in resp.content if hasattr(b, "text"))


def main() -> None:
    ap = argparse.ArgumentParser(description="Generate an affiliate content set for one product.")
    ap.add_argument("--product", help="Full product name/title (required unless --selftest)")
    ap.add_argument("--asin", default="", help="Amazon ASIN (optional)")
    ap.add_argument("--tag", default=DEFAULT_TAG, help=f"Affiliate tag (default {DEFAULT_TAG})")
    ap.add_argument("--model", default=DEFAULT_MODEL, help=f"Claude model (default {DEFAULT_MODEL})")
    ap.add_argument("--output", default="", help="Override output path")
    ap.add_argument("--dry-run", action="store_true", help="Skip the API call; emit the prompt only")
    ap.add_argument("--selftest", action="store_true", help="Run internal asserts and exit")
    args = ap.parse_args()

    if args.selftest:
        assert slug("penkou Portable Neck Fan, Hands Free") == "penkou-portable-neck-fan-hands-free"
        assert slug("!!!") == "product"
        p = build_prompt("Widget", "B0TEST12345", "tag-99")
        assert "Widget" in p and "B0TEST12345" in p and "tag-99" in p
        assert "ASIN:" not in build_prompt("Widget", "", "tag-99")  # asin line omitted
        print("selftest OK")
        return

    if not args.product:
        ap.error("--product is required (or use --selftest)")

    body = generate(args.product, args.asin, args.tag, args.dry_run, args.model)
    out = Path(args.output) if args.output else OUT_DIR / f"{slug(args.product)}-content-set.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(header(args.product, args.asin, args.tag) + body, encoding="utf-8")
    print(f"[content-set] wrote {out}")


if __name__ == "__main__":
    main()
