"""Commit generated guides + (optionally) trigger rsync deploy.

Strategy: stage the whole generated-guides directory then check if anything
ended up in the index. Avoids fragile porcelain parsing — works whether the
directory is fully untracked or only has incremental new/modified files.

Usage:
    python scripts/5_publish.py                   # commit only
    python scripts/5_publish.py --deploy          # commit + npm run deploy:rsync
    python scripts/5_publish.py --no-push         # commit but don't git push
    python scripts/5_publish.py --dry-run         # log what would happen
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import List

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from lib.config import CONFIG, REPO_ROOT  # noqa: E402
from lib.publish import commit, current_branch, deploy_rsync, push  # noqa: E402
from lib.tracking import append_published  # noqa: E402


def _git(args: List[str]) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git", *args],
        cwd=str(REPO_ROOT),
        capture_output=True,
        text=True,
        check=False,
    )


def _staged_files_in(dir_relpath: str) -> List[Path]:
    res = _git(["diff", "--cached", "--name-only", "--", dir_relpath])
    out = []
    for line in res.stdout.splitlines():
        line = line.strip()
        if line.endswith(".json"):
            out.append((REPO_ROOT / line).resolve())
    return out


def main():
    ap = argparse.ArgumentParser(description="Commit + (optionally) deploy generated articles.")
    ap.add_argument("--deploy", action="store_true", help="Also run npm run deploy:rsync after commit.")
    ap.add_argument("--no-push", action="store_true", help="Skip git push.")
    ap.add_argument("--dry-run", action="store_true", help="Print actions without executing.")
    ap.add_argument(
        "--include-guides-ts",
        action="store_true",
        help="Also stage site/app/lib/guides.ts (e.g. after editing the loader).",
    )
    args = ap.parse_args()

    if args.dry_run:
        os.environ["GROWTH_ENGINE_DRY_RUN"] = "1"

    out_dir = Path(CONFIG["paths"]["generated_guides_dir"])
    if not out_dir.exists():
        print(f"[publish] No generated guides directory at {out_dir}.")
        return

    dir_relpath = str(out_dir.resolve().relative_to(REPO_ROOT))

    # Stage the whole guides-generated/ directory in one shot.
    if args.dry_run:
        print(f"[publish] [DRY RUN] git add {dir_relpath}")
    else:
        res = _git(["add", "--", dir_relpath])
        if res.returncode != 0:
            print(f"[publish] git add failed: {res.stderr}")
            sys.exit(1)

    # Optionally also stage the loader edit
    if args.include_guides_ts:
        guides_ts_rel = "site/app/lib/guides.ts"
        if (REPO_ROOT / guides_ts_rel).exists():
            if args.dry_run:
                print(f"[publish] [DRY RUN] git add {guides_ts_rel}")
            else:
                _git(["add", "--", guides_ts_rel])

    # Check what actually ended up staged in the guides dir.
    if args.dry_run:
        # Pretend we staged everything currently in the directory
        staged_paths = sorted(out_dir.glob("*.json"))
    else:
        staged_paths = _staged_files_in(dir_relpath)

    if not staged_paths:
        print("[publish] Nothing new to commit (no changes staged).")
        if args.deploy:
            print("[publish] --deploy set — running rsync anyway (re-deploys current build).")
            try:
                print(deploy_rsync())
            except Exception as e:
                print(f"[publish] deploy failed: {e}")
                sys.exit(1)
        return

    print(f"[publish] {len(staged_paths)} file(s) staged for commit:")
    for p in staged_paths:
        try:
            rel = p.relative_to(REPO_ROOT)
        except ValueError:
            rel = p
        print(f"  + {rel}")

    # Build a useful commit message from the staged files' titles.
    titles: List[str] = []
    for p in staged_paths:
        try:
            obj = json.loads(p.read_text(encoding="utf-8"))
            titles.append(obj.get("title", p.stem))
        except Exception:
            titles.append(p.stem)

    msg_lines = [
        "growth-engine: publish " + (titles[0] if titles else "generated content"),
        "",
    ]
    if len(titles) > 1:
        msg_lines.append("Articles:")
        for t in titles:
            msg_lines.append(f"- {t}")
        msg_lines.append("")
    msg_lines.append(f"Generated by growth-engine at {datetime.now(timezone.utc).isoformat()}")
    msg = "\n".join(msg_lines)

    print("[publish] Committing...")
    print(commit(msg))

    if not args.no_push:
        branch = current_branch()
        print(f"[publish] Pushing to origin/{branch}...")
        try:
            print(push(branch))
        except Exception as e:
            print(f"[publish] git push failed (non-fatal): {e}")

    for p in staged_paths:
        if p.suffix == ".json" and p.exists():
            try:
                obj = json.loads(p.read_text(encoding="utf-8"))
                append_published(
                    {"slug": obj.get("slug"), "title": obj.get("title"), "path": str(p)}
                )
            except Exception:
                pass

    if args.deploy:
        print("[publish] Running deploy:rsync...")
        try:
            print(deploy_rsync())
        except Exception as e:
            print(f"[publish] deploy failed: {e}")
            sys.exit(1)
    else:
        print("[publish] Skipped deploy. Pass --deploy to rsync to hotproductsdot.com.")


if __name__ == "__main__":
    main()
